on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: CodeQL Init
      uses: github/codeql-action/init@v3
      with:
        languages: javascript
        build-mode: none
    - name: CodeQL Analyze
      uses: github/codeql-action/analyze@v3
      with:
        category: "security"
        output: sarif-results
        upload: false
    - name: Test
      run: ls sarif-results
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5.2.0
      with:
        projectBaseDir: .
        args: > 
          -Dsonar.projectKey=JuiceShop
          -Dsonar.sarifReportPaths=sarif-results/javascript.sarif
          -X
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    - name: Wait for SQ
      run: sleep 30
    - name: Send fetch request to DD
      run: |
        curl -X 'POST' \
        'https://dd.innosec.ru/api/v2/import-scan/' \
        -H 'accept: application/json' \
        -H 'Content-Type: multipart/form-data'   \
        -H 'Authorization: Token ${{ secrets.DD_TOKEN }}'  \
        -F 'active=true'   \
        -F 'verified=true'   \
        -F 'scan_type=SonarQube API Import'   \
        -F 'api_scan_configuration=1' \
        -F 'engagement=5' \
        -F 'deduplication_on_engagement=1'
    