on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build JuiceShop
      run: docker build -t juiceshop ./
    - name: Manual Trivy Setup
      uses: aquasecurity/setup-trivy@v0.2.0
      with:
        cache: true
        version: v0.63.0
    - name: Trivy Scan
      run: trivy image --security-checks vuln --format cyclonedx --output result.json juiceshop
    - uses: DependencyTrack/gh-upload-sbom@v3
      with:
        protocol: https
        serverHostname: ${{ secrets.DEPENDENCYTRACK_HOSTNAME }}
        port: ${{ secrets.DEPENDENCYTRACK_PORT }}
        apiKey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
        projectName: 'JuiceShop'
        projectVersion: 'master'
        bomFilename: "result.json"
        autoCreate: false
