on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build JuiceShop
      run: docker build -t juiceshop ./
    - name: Manual Trivy Setup
      uses: aquasecurity/setup-trivy@v0.2.0
      with:
        cache: true
        version: v0.63.0
    - name: Trivy Scan
      run: trivy image --security-checks vuln --format cyclonedx --output result.json juiceshop
    - name: Upload Trivy scan to DT
      run: |
        curl -X "POST" "https://${{ secrets.DEPENDENCYTRACK_HOSTNAME }}/api/v1/bom" \
          -H 'Content-Type: multipart/form-data' \
          -H 'X-Api-Key: ${{ secrets.DEPENDENCYTRACK_APIKEY }}' \
          -F "projectName=JuiceShop" \
          -F "bom=@result.json" \
          -F "autoCreate=true" \