on:
  push:
    branches: [ "master" ]

  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install shop
      run: npm install
    - name: Run shop
      run: npm start &
    - name: Wait for shop
      run: sleep 20s
    - name: ZAP Scan
      uses: zaproxy/action-baseline@7c4deb10e6261301961c86d65d54a516394f9aed # v0.14.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target: 'http://localhost:3000'
        rules_file_name: '.zap/rules.tsv'
        cmd_options: '-x ./zap_report.xml'
    - name: Send report
      run: |
        curl -X 'POST' \
        'https://dd.innosec.ru/api/v2/import-scan/' \
        -H 'accept: application/json' \
        -H 'Content-Type: multipart/form-data'   \
        -H 'Authorization: Token ${{ secrets.DD_TOKEN }}'  \
        -F 'active=true'   \
        -F 'verified=true'   \
        -F 'scan_type=ZAP Scan'   \
        -F 'file=@zap_report.xml;type=text/xml' \
        -F 'engagement=5' 
